tap "facebook/fb"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "keith/formulae"

brew "apr-util"
brew "aspell"
brew "fzf"
brew "lf"
brew "automake"
brew "awscli"
brew "bash"
brew "bazel",   
brew "bazelisk",
brew "boost"
brew "glib"
brew "pkg-config"
brew "cairo"
brew "cmake"
brew "cocoapods"
brew "coreutils"
brew "diff-so-fancy"
brew "direnv"
brew "guile"
brew "unbound"
brew "gnutls"
brew "fd"
brew "harfbuzz"
brew "libass"
brew "srt"
brew "ffmpeg"
brew "findutils"
brew "git"
brew "git-lfs"
brew "go"
brew "grep"
brew "grpc"
brew "htop"
brew "httpie"
brew "hub"
brew "jq"
brew "languagetool"
brew "lazygit"
brew "libvterm"
brew "luv"
brew "mackup"
brew "mas"
brew "maven"
brew "neovim"
brew "nghttp2"
brew "node"
brew "nvm"
brew "poppler"
brew "qt"
brew "ruby-build"
brew "rbenv"
brew "ripgrep"
brew "ruby"
brew "shellcheck"
brew "subversion"
brew "swift-format"
brew "swiftlint"
brew "the_silver_searcher"
brew "tmux"
brew "trash"
brew "tree"
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "midnight-commander"
brew "inav"
brew "less"
brew "git-delta"
brew "jordanbaird-ice"      # Menu bar organiser

# Apps
cask "cheatsheet"
cask "dropbox"
cask "eul"                  # System monitor
cask "flipper"              # App debugger
cask "hammerspoon"
cask "proxyman"
cask "iterm2"
cask "raycast"
cask "steam"
cask "trader-workstation"
cask "transmission"
cask "cursor"               # Text editor
cask "vlc"
cask "shottr"
cask "mate-translate"
cask "sf-symbols"
cask "android-studio"
cask "arc"                   # browser
cask "clop"                  # Image, Video & PDF optimizer
cask "monitorcontrol"        # When working with external monitors
cask "slack"
cask "nikitabobko/tap/aerospace"

