theme = "sonokai"

[editor]
line-number = "relative"
mouse = true
true-color = true
cursorline = true
auto-completion = true
auto-format = true
idle-timeout = 0
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
C-s = ":w" # Maps Ctrl-s to the typable command :w which is an alias for :write (save file)
C-o = ":open ~/.config/helix/config.toml" # Maps Ctrl-o to opening of the helix config file
g = { a = "code_action" } # Maps `ga` to show possible code actions

# Views
C-h = "jump_view_left"
C-l = "jump_view_right"
C-j = "jump_view_down"
C-k = "jump_view_up"


